M48
; DRILL file {KiCad (6.0.1)} date Tue Feb 15 16:57:25 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-15T16:57:25-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X5.5235Y-3.5565
X5.7243Y-3.521
X5.7243Y-4.0486
X6.0235Y-3.5525
T2
X5.635Y-3.885
X5.885Y-3.985
T0
M30
